(* ::Package:: *)

(* ::Input:: *)
(*ClearAll["Global"];*)


(* ::Input:: *)
(*(*Defining coordinates and metric*)*)
(*coords={t,r,\[Theta],\[Phi]};*)
(*dim=Length[coords];*)
(*\[Eta]metric={{1,0,0,0},{0,-1,0,0},{0,0,-1,0},{0,0,0,-1}};*)
(*metric=DiagonalMatrix[{Exp[2 A[r]],-Exp[2 B[r]],-r^2,-r^2 Sin[\[Theta]]^2}];*)
(*invMetric=Simplify[Inverse[metric]];*)
(*Print["Metric g_{\[Mu]\[Nu]} ="];*)
(*metric // MatrixForm*)
(*Print["Inverse metric g^{\[Mu]\[Nu]} ="];*)
(*invMetric // MatrixForm*)


(* ::Input:: *)
(*(*Christoffel Connections*)*)
(*Christoffel[\[Mu]_,\[Nu]_,\[Rho]_]:=1/2 Sum[invMetric[[\[Mu],\[Sigma]]] (D[metric[[\[Sigma],\[Nu]]],coords[[\[Rho]]]]+D[metric[[\[Sigma],\[Rho]]],coords[[\[Nu]]]]-D[metric[[\[Nu],\[Rho]]],coords[[\[Sigma]]]]),{\[Sigma],4}];*)
(**)
(*\[CapitalGamma]=Table[Simplify[Christoffel[\[Mu],\[Nu],\[Rho]]],{\[Mu],4},{\[Nu],4},{\[Rho],4}];*)
(**)
(*Print["Nonzero Christoffel symbols:"];*)
(*Select[*)
(*  Flatten[*)
(*    Table[{\[Mu], \[Nu], \[Rho]} -> \[CapitalGamma][[\[Mu], \[Nu], \[Rho]]],*)
(*      {\[Mu], 4}, {\[Nu], 4}, {\[Rho], 4}],*)
(*    2],*)
(*  #[[2]] =!= 0 &*)
(*] // TableForm*)


(* ::Input:: *)
(*(*Tetrad Field*)*)
(*tetrad = {*)
(*{Exp[A[r]] Cosh[\[Alpha][r, \[Theta]]], 0, 0, r Sin[\[Theta]] Sinh[\[Alpha][r, \[Theta]]]},*)
(*{0,  Exp[B[r]] Sin[\[Rho][r, \[Theta]]], -r Cos[\[Rho][r, \[Theta]]], 0},*)
(*{Exp[A[r]] Sinh[\[Alpha][r, \[Theta]]], 0, 0, r Sin[\[Theta]] Cosh[\[Alpha][r, \[Theta]]]},*)
(*{0, -Exp[B[r]] Cos[\[Rho][r, \[Theta]]], -r Sin[\[Rho][r, \[Theta]]], 0}*)
(*};*)
(*Print["Tetrad e^a_\[Mu] ="];*)
(*tetrad // TableForm*)
(**)
(*(*Inverse tetrad field*)*)
(*invtetrad= Table[Sum[\[Eta]metric[[a,b]]*invMetric[[\[Mu],\[Nu]]]*tetrad[[b,\[Nu]]],{\[Nu],dim},{b,dim}],{a,dim},{\[Mu],dim}]*)


(* ::Input:: *)
(*(*Verifying properties of tetrad and inverse tetrad*)*)
(*Simplify[Table[Sum[\[Eta]metric[[n,m]]*tetrad[[n,\[Mu]]]*tetrad[[m,\[Nu]]],{n,1,4},{m,1,4}],{\[Mu],4},{\[Nu],4}]]*)
(**)


(* ::Input:: *)
(*Simplify[Table[Sum[metric[[\[Mu],\[Nu]]]*invtetrad[[n,\[Mu]]]*invtetrad[[m,\[Nu]]],{\[Mu],1,4},{\[Nu],1,4}],{n,4},{m,4}]]*)


(* ::Input:: *)
(*Table[Sum[tetrad[[i,n]]*invtetrad[[j,n]],{n,4}],{i,4},{j,4}]//Simplify*)


(* ::Input:: *)
(*(*Pauli Matrices*)*)


(* ::Input:: *)
(*\[Sigma]1 = {{0, 1}, {1, 0}};*)
(*\[Sigma]2 = {{0, -I}, {I, 0}};*)
(*\[Sigma]3 = {{1, 0}, {0, -1}};*)
(**)
(*(*Gamma Matrices*)*)
(*\[Gamma]0 = ArrayFlatten[{{ConstantArray[0,{2,2}],IdentityMatrix[2]},{IdentityMatrix[2],ConstantArray[0,{2,2}]}}]*)
(**)
(*\[Gamma]i[i_] := ArrayFlatten[{{0, \[Sigma]i[i]}, {-\[Sigma]i[i], 0}}];*)
(**)
(*\[Sigma]i[1] = \[Sigma]1; \[Sigma]i[2] = \[Sigma]2; \[Sigma]i[3] = \[Sigma]3;*)
(**)
(*gammaFlat = {\[Gamma]0,\[Gamma]i[1], \[Gamma]i[2], \[Gamma]i[3]};*)
(**)
(*Print["Flat gamma matrices:"];*)
(*Do[*)
(*  Print["\[Gamma]^", a, " ="];*)
(*  Print[ gammaFlat[[a]] // MatrixForm ],*)
(*  {a, 4}*)
(*]*)
(**)
(**)
(*gammaCurved[\[Mu]_] :=*)
(*  Sum[invtetrad[[a, \[Mu]]] gammaFlat[[a]], {a, 4}];*)
(**)
(*Print["Curved gamma matrices \[Gamma]^\[Mu](x):"];*)
(*Do[*)
(*  Print["\[Gamma]^", \[Mu], "(x) ="];*)
(*  Print[ gammaCurved[\[Mu]] // MatrixForm ],*)
(*  {\[Mu], 4}*)
(*]*)


(* ::Input:: *)
(*(*Spin Connection Coefficients Subscript[\[Omega]^a, \[Mu]b]*)*)
(*spinConnection[\[Mu]_, a_, b_] :=*)
(*  Sum[*)
(*    tetrad[[a,\[Nu]]] ( *)
(*      D[invtetrad[[b, \[Nu]]], coords[[\[Mu]]]] +*)
(*      Sum[\[CapitalGamma][[\[Nu], \[Mu], \[Lambda]]] invtetrad[[b, \[Lambda]]], {\[Lambda], 4}]*)
(*    ),*)
(*    {\[Nu], 4}*)
(*  ];*)
(**)
(*Print["Nonzero spin connection components \[Omega]_{\[Mu]ab}:"];*)
(*Select[*)
(*  Flatten[*)
(*    Table[{\[Mu], a, b} -> spinConnection[\[Mu], a, b],*)
(*      {\[Mu], 4}, {a, 4}, {b, 4}],*)
(*    2],*)
(*  #[[2]] =!= 0 &*)
(*] // TableForm*)


(* ::Input:: *)
(*(*Lowering Index Subscript[\[Omega], \[Mu]ab] by contracting with Subscript[\[Eta], ab]*)*)
(*spinConnectiondown[\[Mu]_, a_, b_] :=*)
(*  Sum[\[Eta]metric[[a,c]]*spinConnection[\[Mu],c,b],{c,1,4}];*)
(**)
(*Print["Nonzero spin connection components \[Omega]_{\[Mu]ab}:"];*)
(*Select[*)
(*  Flatten[*)
(*    Table[{\[Mu], a, b} -> spinConnectiondown[\[Mu], a, b],*)
(*      {\[Mu], 4}, {a, 4}, {b, 4}],*)
(*    2],*)
(*  #[[2]] =!= 0 &*)
(*] // TableForm*)


(* ::Input:: *)
(*(*Defining the Dirac Operator *)
(*i\[Gamma]^\[Mu]Subscript[D, \[Mu]]\[Psi]-m\[Psi]*)*)
(*(*diracEqn[\[Psi]_]:=\[ImaginaryI](Sum[gammaCurved[\[Mu]].D[\[Psi],coords[[\[Mu]]]],{\[Mu],1,4}]-1/4Sum[gammaCurved[\[Mu]].Sum[spinConnectiondown[\[Mu],a,b]*gammaFlat[[a]].gammaFlat[[b]](*-gammaFlat[[b]].gammaFlat[[a]]*),{a,1,4},{b,1,4}],{\[Mu],1,4}].(\[Psi]))-m*\[Psi];*)*)
(*diracEqn[\[Psi]_]:=I *(Sum[gammaCurved[\[Mu]] . (D[\[Psi],coords[[\[Mu]]]]),{\[Mu],1,4}])-I/4* Sum[gammaCurved[\[Mu]] . Sum[spinConnectiondown[\[Mu],e,f]*(gammaFlat[[e]] . gammaFlat[[f]] . \[Psi]),{e,1,4},{f,1,4}],{\[Mu],1,4}]-m \[Psi];*)


(* ::Input:: *)
(*(*Defining the \[Psi] ansatz (can be chosen as per your case)*)*)
(*\[Psi] = E^(nu[r,\[Theta]]/2)/(r Sqrt[Sin[\[Theta]]]) E^(-I(m*t-L*\[Phi])) {*)
(*  E^(I*b[r,\[Theta]]/2),*)
(*  0,*)
(*  E^(-I*b[r,\[Theta]]/2),*)
(*  0*)
(*};*)


(* ::Input:: *)
(*(*Solving the Dirac equations simultaneously*)*)
(*eqn1=Simplify[diracEqn[\[Psi]][[1]]/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x1/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x2/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x3/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x4,Assumptions->{r\[Element]PositiveReals,\[Theta]\[Element]PositiveReals,r>0,\[Theta]>0,\[Theta]<\[Pi]}]*)
(*eqn2=Simplify[diracEqn[\[Psi]][[2]]/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x1/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x2/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x3/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x4,Assumptions->{r\[Element]PositiveReals,\[Theta]\[Element]PositiveReals,r>0,\[Theta]>0,\[Theta]<\[Pi]}]*)
(*eqn3=Simplify[diracEqn[\[Psi]][[3]]/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x1/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x2/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x3/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x4,Assumptions->{r\[Element]PositiveReals,\[Theta]\[Element]PositiveReals,r>0,\[Theta]>0,\[Theta]<\[Pi]}]*)
(*eqn4=Simplify[diracEqn[\[Psi]][[4]]/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x1/.\!\(\*SuperscriptBox[\(nu\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x2/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", ",", "0"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x3/.\!\(\*SuperscriptBox[\(b\), *)
(*TagBox[*)
(*RowBox[{"(", *)
(*RowBox[{"0", ",", "1"}], ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[r,\[Theta]]->x4,Assumptions->{r\[Element]PositiveReals,\[Theta]\[Element]PositiveReals,r>0,\[Theta]>0,\[Theta]<\[Pi]}]*)


(* ::Input:: *)
(*sol=Solve[{eqn1==0,eqn2==0,eqn3==0,eqn4==0},{x1,x2,x3,x4}]//Simplify*)


(* ::Input:: *)
(*ComplexExpand[x1/.sol[[1,1]]]//Simplify*)


(* ::Input:: *)
(*ComplexExpand[x2/.sol[[1,2]]]//Simplify*)


(* ::Input:: *)
(*ComplexExpand[x3/.sol[[1,3]]] //Simplify*)


(* ::Input:: *)
(*ComplexExpand[x4/.sol[[1,4]]]//Simplify*)
